# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sbom-diff"
BBFILE_PATTERN_meta-sbom-diff = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sbom-diff = "6"

LAYERDEPENDS_meta-sbom-diff = "core"
LAYERSERIES_COMPAT_meta-sbom-diff = "scarthgap"

LAYERDIR_SBOM_SCRIPTS = "${LAYERDIR}"
